# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.22.1"
gem "rspec", "~> 3.12"
gem "debug", "~> 1.7"
